FROM node:alpine as build

WORKDIR /expensify
 
COPY . ./

RUN yarn

RUN yarn build

# production environment
FROM nginx:stable-alpine

COPY --from=build /expensify/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]